### ISSUE TITLE
likelovewant also provides rocmlibs for other gpu

### ISSUE THREAD

**Issue by xhebox** [CS1o/Stable-Diffusion-Info#1]
I've tested with HIP 6.1.2 and gfx1031 with comfyui, working normally.

**Comment by CS1o** [comment]
Thanks for letting me know!
I will update all Zluda Guides again for the older GPUs.

**Comment by CS1o** [comment]
Updated the Guides for all Webuis and GPUs to use ROCm HIP SDK 6.1.2
