### ISSUE TITLE
Automatic1111 without error info when pressing create

### ISSUE THREAD

**Issue by Markznm** [CS1o/Stable-Diffusion-Info#4]
Crashes without error info when pressing create
I have RX 580 2048SP (Maybe rx470 because aliexpress sellers often use its chip in rx580 2048sp refabs)
Driver version 24.7.1 and ROCm 5.7.1
Log:
```
Microsoft Windows [Version 10.0.19045.2673]
(c) Корпорация Майкрософт (Microsoft Corporation). Все права защищены.

C:\SD-Zluda\stable-diffusion-webui-amdgpu>webui-user.bat
venv "C:\SD-Zluda\stable-diffusion-webui-amdgpu\venv\Scripts\Python.exe"
WARNING: ZLUDA works best with SD.Next. Please consider migrating to SD.Next.
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: v1.10.1-amd-2-g395ce8dc
Commit hash: 395ce8dc2cb01282d48074a89a5e6cb3da4b59ab
Using ZLUDA in C:\SD-Zluda\stable-diffusion-webui-amdgpu\.zluda
Skipping onnxruntime installation.
You are up to date with the most recent release.
no module 'xformers'. Processing without...
no module 'xformers'. Processing without...
No module 'xformers'. Proceeding without it.
C:\SD-Zluda\stable-diffusion-webui-amdgpu\venv\lib\site-packages\pytorch_lightning\utilities\distributed.py:258: LightningDeprecationWarning: `pytorch_lightning.utilities.distributed.rank_zero_only` has been deprecated in v1.8.1 and will be removed in v2.0.0. You can import it from `pytorch_lightning.utilities` instead.
  rank_zero_deprecation(
Launching Web UI with arguments: --use-zluda --update-check --skip-ort
Loading weights [6ce0161689] from C:\SD-Zluda\stable-diffusion-webui-amdgpu\models\Stable-diffusion\v1-5-pruned-emaonly.safetensors
Creating model from config: C:\SD-Zluda\stable-diffusion-webui-amdgpu\configs\v1-inference.yaml
C:\SD-Zluda\stable-diffusion-webui-amdgpu\venv\lib\site-packages\huggingface_hub\file_download.py:1150: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 26.0s (prepare environment: 29.1s, initialize shared: 5.8s, other imports: 1.2s, load scripts: 1.3s, create ui: 1.6s, gradio launch: 0.7s).
Applying attention optimization: Doggettx... done.
Для продолжения нажмите любую клавишу . . .
```
I can give more info if needed

**Comment by RenanOSX** [comment]
same here

**Comment by Markznm** [comment]
> Hey, the RX580 is a bit harder to get work.
> 
> Make sure your AMD Adrenalin Driver is Updated. Also make sure you have 16gb RAM or more. You should place only one 2gb model file inside the models/stable-diffusion folder for startup to prevent loading anything bigger which could crash.
> 
> Also try out the steps from here: [#2 (comment)](https://github.com/CS1o/Stable-Diffusion-Info/issues/2#issuecomment-2292267005)
> 
> And then the last FIX is a bit wierd but worked for someone with the same error: Relaunch the webui-user.bat and press generate. - it will crash. Relaunch and try to generate again. Do this 10-15 times and it eventually could start to work, no joke. If its frozen dont interrupt it. (that means it processes zluda/cuda stuff in the background). Only close when it crashes with the same error from above, then relaunch.
> 
> Let me know if it worked.

Thanks, i'll try!

**Comment by RenanOSX** [comment]
> Hey, the RX580 is a bit harder to get work.
> 
> Make sure your AMD Adrenalin Driver is Updated. Also make sure you have 16gb RAM or more. You should place only one 2gb model file inside the models/stable-diffusion folder for startup to prevent loading anything bigger which could crash.
> 
> Also try out the steps from here: [#2 (comment)](https://github.com/CS1o/Stable-Diffusion-Info/issues/2#issuecomment-2292267005)
> 
> And then the last FIX is a bit wierd but worked for someone with the same error: Relaunch the webui-user.bat and press generate. - it will crash. Relaunch and try to generate again. Do this 10-15 times and it eventually could start to work, no joke. If its frozen dont interrupt it. (that means it processes zluda/cuda stuff in the background). Only close when it crashes with the same error from above, then relaunch.
> 
> Let me know if it worked.

Actually this works, just keep trying over and over at one point will work, even tho is not 100% perfect, just open the webui-user 5-6 times and it should skip the "Applying attention optimization: Doggettx... done."

Thanks for the help!

**Comment by aluisperezh** [comment]
After trying almost everything and bing used to relaunch several times, I've fixed this problem just by adding "--no-half" to the parameters in webui-user.bat. It works always the first time.

On the other hand, all my generations (one by one or in a batch) take a very long time to finish, even when they are at 100%. Still trying to find out why and how to solve it.

Regards.

**Comment by CS1o** [comment]
> After trying almost everything and being used to relaunch several times, I've fixed this problem just by adding "--no-half" to the parameters in webui-user.bat. It works always the first time.

Whats your GPU?
--no-half does use a lot more vram. only a hand full of old gpus need it. With using ZLUDA it shouldnt be needed.
What settings do you use when it takes so long?
Can you provide more Information? txt2img settings like resolution, model, etc. and maybe a cmd log?

**Comment by aluisperezh** [comment]
It's an RX580, as for the first messages. And I have the same problem detailed there. Most of the times the server just stops without any message ("Press any key to continue..." and then it quits the CMD shell). With "--no-half" it works always.

My cli arguments: "**--use-zluda --update-check --skip-ort --ckpt-dir 'C:\stable-diffusion-webui-amdgpu\models\Stable-diffusion' --lora-dir 'C:\stable-diffusion-webui-amdgpu\models\Lora**'"
With these environment variables:
**set HF_DATASETS_OFFLINE=1
set HF_HUB_OFFLINE=1**
Just to avoid the error when trying to download a model from HuggingFace on start.

It doesn't matter which model I use, it always happens the same: generation is fast (about 12  it/s or faster) but then it just stops responding for a looong while. I tried setting all the debug options I know about (not many, tbh), but I never get any clue about what's happening. One of the GPU "Compute" graphics in the task manager of Windows shows it's working at 100% most of the time, butb that's all.

This is a typical output (you can see the difference in speed between the generation and whatever it happens later: 11.88it/S vs 6.13s/it):
`Model loaded in 4.2s (load weights from disk: 0.5s, create model: 0.3s, apply weights to model: 2.6s, load VAE: 0.2s, load textual inversion embeddings: 0.1s, calculate empty prompt: 0.3s).
100%|██████████████████████████████████████████████████████████████████████████████████| 30/30 [00:02<00:00, 11.88it/s]
Total progress: 100%|██████████████████████████████████████████████████████████████████| 30/30 [03:03<00:00,  6.13s/it]
{"prompt": "medieval castle in ruins on a hill over a river", "all_prompts": ["medieval castle in ruins on a hill over a river"], "negative_prompt": "", "all_negative_prompts": [""], "seed": 1420111069, "all_seeds": [1420111069], "subseed": 3653969883, "all_subseeds": [3653969883], "subseed_strength": 0, "width": 512, "height": 768, "sampler_name": "DPM++ 2M", "cfg_scale": 7, "steps": 30, "batch_size": 1, "restore_faces": false, "face_restoration_model": null, "sd_model_name": "v1-5-pruned-emaonly", "sd_model_hash": "6ce0161689", "sd_vae_name": "vae-ft-ema-560000-ema-pruned.ckpt", "sd_vae_hash": "0b204ad0ca", "seed_resize_from_w": -1, "seed_resize_from_h": -1, "denoising_strength": 0.7, "extra_generation_params": {"Schedule type": "Karras"}, "index_of_first_image": 0, "infotexts": ["medieval castle in ruins on a hill over a river\nSteps: 30, Sampler: DPM++ 2M, Schedule type: Karras, CFG scale: 7, Seed: 1420111069, Size: 512x768, Model hash: 6ce0161689, Model: v1-5-pruned-emaonly, VAE hash: 0b204ad0ca, VAE: vae-ft-ema-560000-ema-pruned.ckpt, Version: v1.10.1-amd-11-gefddd05e"], "styles": [], "job_timestamp": "20241012172708", "clip_skip": 1, "is_using_inpainting_conditioning": false, "version": "v1.10.1-amd-11-gefddd05e"}`

Thanks for your work and for trying to solve this.

**Comment by CS1o** [comment]
Hmm, i heard of that speed bug that appears only with 1.5 based models.
What you can try is to use these updated ROCm Library Files for the RX580 (gfx803):
For HIP SDK 5.7: https://github.com/likelovewant/ROCmLibs-for-gfx1103-AMD780M-APU/releases/download/v0.5.7/rocm.gfx803.optic.test.version.7z

Or you can try uninstall HIP SDK 5.7 and install 6.1 and then use these library files:
https://github.com/likelovewant/ROCmLibs-for-gfx1103-AMD780M-APU/releases/download/v0.6.1.2/rocm.gfx803.optic.vega10.logic.hip.sdk.6.1.2.7z

Let me know if one of these options work.

**Comment by aluisperezh** [comment]
I had already tried both, but I'll do it again.

First one (new libraries for 5.7) doesn't work. It can't even finish a generation.

Will try updating to SDK 6.1 as soon as I can.

By the way. I don't know if the bug only affects 1.5 models, with SDXL it takes about 10 minutes to complete a generation and the results are really bad. DirectML works much better.

Thanks again

**Comment by CS1o** [comment]
For SDXL and GPUs with 8gb vram try adding `--medvram-sdxl` to the webui-user.bat, that should speed up the generation.

**Comment by aluisperezh** [comment]
Hello again.

I've been trying to make SD, SD.Next, Fooocus and ComfyUI with ROCm 6.1, but I wasn't able. I could never get the RX580 being recognised. The result always something like "ROCm agent not found" or an error about caffe. WIll keep on trying both with 5.7 and 6.1.

Thanks for your support and regards

**Comment by brsh1** [comment]
did anybody got rx580 working with zluda? I've tried on the same system with both RX580 and RX VEGA64.
RX VEGA 64 - Works @ 2/sec per iteration
RX 580 fails to run  with this error:

17:40:16-511684 WARNING  ZLUDA support: experimental
17:40:16-586389 WARNING  Failed to load ZLUDA: [WinError 1114] A dynamic link library (DLL) initialization routine
                         failed1
                         
I've tried replacing the library files for 5.7 and same persists.

**Comment by CS1o** [comment]
> I've been trying to make SD, SD.Next, Fooocus and ComfyUI with ROCm 6.1, but I wasn't able. I could never get the RX580 being recognised. The result always something like "ROCm agent not found" or an error about caffe. WIll keep on trying both with 5.7 and 6.1.

To get the RX580 (gfx803) working with HIP SDK 6.1 you need the correct librarys to replace:
https://github.com/likelovewant/ROCmLibs-for-gfx1103-AMD780M-APU/releases/download/v0.6.1.2/rocm.gfx803.optic.vega10.logic.hip.sdk.6.1.2.7z
Replace the files in the rocblas/library with these.

**Comment by CS1o** [comment]
> did anybody got rx580 working with zluda? I've tried on the same system with both RX580 and RX VEGA64. RX VEGA 64 - Works @ 2/sec per iteration RX 580 fails to run with this error:

@brsh1 
we had 3 people in the issues that got it working in the end. And a lot more in the SD discord.
Make sure you have only hip sdk rocm 5.7 or 6.1 installed, not both.
then use the correct library files.
You should use the Vega64 if you can. Its the better card.

**Comment by aluisperezh** [comment]
> > I've been trying to make SD, SD.Next, Fooocus and ComfyUI with ROCm 6.1, but I wasn't able. I could never get the RX580 being recognised. The result always something like "ROCm agent not found" or an error about caffe. WIll keep on trying both with 5.7 and 6.1.
> 
> @aluisperezh To get the RX580 (gfx803) working with HIP SDK 6.1 you need the correct librarys to replace: https://github.com/likelovewant/ROCmLibs-for-gfx1103-AMD780M-APU/releases/download/v0.6.1.2/rocm.gfx803.optic.vega10.logic.hip.sdk.6.1.2.7z Replace the files in the rocblas/library with these.

I've tried these libraries many times: with Adrenaline drivers, with PRO drivers, uninstalling previous drivers and ROCm libraries, even using AMD cleanup utility and video driver uninstaller. The result is always the same: 
  - "WARNING: no ROCm agent was found!" (stable-diffusion-webui-amdgpu)
  - AMD ROCm toolkit detected
    ROCm agents detected: []
    ROCm version detected: 6.1 (SD.next)

I tried to check the source code to find out if there was any difference in the detection of gfx803 in libs for 5.7 and 6.1, but I couldn't find the source code (or my ancient programming skills are not enough to read it, maybe). In "likelovewant" GitHub page I can only find the libraries.

Why I'm trying to find differences? I think my RX580 is different from "standard" RX580: while "standard" device code is something like "1002 67DF", mine is "1002 6**F**DF". Maybe the libs check this, I couldn't find it out...

Regards and thanks again for your support.

**Comment by CS1o** [comment]
The librarys should work. But the error "no ROCm Agent found" doesnt have to do with the gpu at all.
It means either HIP SDK wasnt installed or you didnt added %HIP_PATH%bin into the System variable Path correctly.
Maybe share a screenshot of your Path settings.

**Comment by aluisperezh** [comment]
I think I did everything OK, step by step. Indeed, I tried the same in my laptop, with an AMD Ryzen 7 8845HS (Radeon 780M GPU inside) and everuthing is working (more or less...).
![Path y variables](https://github.com/user-attachments/assets/211d22f0-0ff1-4f46-9966-001ceece4148)
You can see that PATH and HIP_PATH variables are OK, and the "agent" message is present...

Thanks again

**Comment by CS1o** [comment]
Okay, can you try delete the venv and the .zluda folder from the stable-diffusion-webui-amdgpu folder and then relaunch?

**Comment by aluisperezh** [comment]
Already did many times with same results. But it seems the problem is somewhere else. In the https://github.com/likelovewant/ROCmLibs-for-gfx1103-AMD780M-APU/releases repository there is this:

```
gfx803:
- rocm.gfx803.optic.vega10.logic.hip.sdk.6.1.2.7z （reported not working)
```

And the author says that there have been changes in ROCm 6.1 he can't control, so it looks like 5.7 is our (RX580 owners) only way :(

Anyway, thanks again for your support and your work.

**Comment by CS1o** [comment]
Oh alright, guess i'll update the Guide then for the RX580.
And no problem!

**Comment by CS1o** [comment]
Guide Updated for RX570 and RX580 (gfx803) Users to use ROCm HIP SDK 5.7
