### ISSUE TITLE
Failed to load ZLUDA: list index out of range

### ISSUE THREAD

**Issue by Gitinian** [CS1o/Stable-Diffusion-Info#5]
No idea why this happens, I followed all the steps in the AMD A1111 ZLUDA guide to the letter.

venv "C:\SD-Zluda\stable-diffusion-webui-amdgpu\venv\Scripts\Python.exe"
WARNING: ZLUDA works best with SD.Next. Please consider migrating to SD.Next.
Python 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
Version: v1.10.1-amd-9-g46397d07
Commit hash: 46397d078cff4547eb4bd87adc5c56283e2a8d20
Using ZLUDA in C:\SD-Zluda\stable-diffusion-webui-amdgpu\.zluda
Failed to load ZLUDA: list index out of range
Using CPU-only torch
Skipping onnxruntime installation.

**Comment by CS1o** [comment]
Whats your GPU?
AMD Driver Version
HIP SDK Version
Restarted the PC once?
Replaced the Rocm library files if needed?

**Comment by Gitinian** [comment]
7900XT
24.10.24
HIP SDK is the one recommended in the post
Yes
No

**Comment by CS1o** [comment]
> 7900XT 24.10.24 HIP SDK is the one recommended in the post Yes No

You need AMD Adrenalin 24.8.1
24.10.24 seems like the Blue Pro Version which doesnt work mostly.
So reinstall the Driver and try again.

**Comment by Gitinian** [comment]
I reinstalled and deleted the folders but it still gives me the error

**Comment by Gitinian** [comment]
It got worse

Launching Web UI with arguments: --use-zluda --update-check --skip-ort
ZLUDA device failed to pass basic operation test: index=None, device_name=AMD Radeon RX 7900 XT [ZLUDA]
CUDA error: operation not supported
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

**Comment by Gitinian** [comment]
It ran before but now it doesnt work at all

**Comment by CS1o** [comment]
> It ran before but now it doesnt work at alWhats your AMD Adrenalin Version now?
Also are your environment paths correct?

**Comment by Gitinian** [comment]
My version is 24.8.1, and I'm pretty sure path doesn't change with adrenalin updates, but I did double check after the crashes, and I added both zluda and hip to the env during the first install

**Comment by CS1o** [comment]
can you share the full cmd log you get now when launching the webui-user.bat?
make sure %HIP_PATH%bin is in the PATH.
"Failed Basic Test" means something is wrong with either the zluda files or the hip sdk path.
Try restartting PC, deleting the .zluda folder in the webui and relaunch.

**Comment by Gitinian** [comment]
uh i reinstalled amd pro 24.10.16, and the sd installation specifically and copied all my webui bat settings and it works now for some reason at 20 it/s without errors. thanks i guess?

**Comment by Gitinian** [comment]
youre awesome for making this guide though. keep putting out fire

**Comment by CS1o** [comment]
hey thanks, nice that it works now.
I guess you had the same error as here: https://github.com/lshqqytiger/stable-diffusion-webui-amdgpu/issues/540

That issue got fixed 16 hours ago by the dev.

**Comment by Gitinian** [comment]
The log looks identical to what I had, seems like this was it.
