### ISSUE TITLE
Auto1111 uses CPU instead of GPU

### ISSUE THREAD

**Issue by Cappyadams** [CS1o/Stable-Diffusion-Info#7]
I have no idea if this is the right place to ask, but for some reason automatic1111 keeps using my CPU instead of my GPU. my GPU is a Radeon RX5700 and even tho it says that it detected ZULDA, I'm still getting an army of errors and it uses my CPU.
![image](https://github.com/user-attachments/assets/effeadf9-7559-464b-b692-404703a61174)
![image](https://github.com/user-attachments/assets/a6acbea2-4d49-4003-9d1c-e02febf26712)
Note: I used [this guide](https://github.com/CS1o/Stable-Diffusion-Info/wiki/Webui-Installation-Guides#amd-automatic1111-with-zluda)

**Comment by CS1o** [comment]
Hey, it shows "no ROCm Agent was found" in the first screenshot.
That means you either not installed HIP SDK or you didnt added %HIP_PATH%bin to the System Environment Path correctly.

**Comment by Cappyadams** [comment]
But I did both? I did it just like it shows-

**Comment by CS1o** [comment]
> But I did both? I did it just like it shows-

Have you restarted the PC?
have you downloaded the custom library files and replaced them in the /library folder?

**Comment by CS1o** [comment]
Closed as no Replay was given.

**Comment by benny7770** [comment]
> But I did both? I did it just like it shows-

one thing that people look over is enabling "add to environment variables" when going through the python install
