### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'split' (Automatic1111 with ZLUDA)

### ISSUE THREAD

**Issue by F1zzyD** [CS1o/Stable-Diffusion-Info#8]
Followed [THIS GUIDE](https://github.com/CS1o/Stable-Diffusion-Info/wiki/Webui-Installation-Guides#amd-automatic1111-with-zluda) from scratch. Installed the prerequisites and ran the webui-user.bat as the guide asked and now I get this:

> Python 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
> Version: v1.10.1-amd-11-gefddd05e
> Commit hash: efddd05e11d9cc5339a41192457e6ff8ad06ae00
> Traceback (most recent call last):
>   File "F:\stable-diffusion-webui-amdgpu\launch.py", line 48, in <module>
>     main()
>   File "F:\stable-diffusion-webui-amdgpu\launch.py", line 39, in main
>     prepare_environment()
>   File "F:\stable-diffusion-webui-amdgpu\modules\launch_utils.py", line 545, in prepare_environment
>     from modules import zluda_installer, rocm
>   File "F:\stable-diffusion-webui-amdgpu\modules\zluda_installer.py", line 16, in <module>
>     HIPSDK_TARGETS = ['rocblas.dll', 'rocsolver.dll', f'hiprtc{"".join([v.zfill(2) for v in rocm.version.split(".")])}.dll']
> AttributeError: 'NoneType' object has no attribute 'split'
> Press any key to continue . . .

I'm assuming the guide is outdated.......

**Comment by CS1o** [comment]
The Guide is not outdated.
Have you installed HIP SDK correctly?
And how do your Path environment variable's look?
What's your GPU?
What's your Adrenalin Version?

**Comment by CS1o** [comment]
Closed since no Reply was given.
